README.md

Just some quick instructions for the readme.

update readme for local dev

---

repl/src/tutorial/Tutorial.js
repl/src/tutorial/style.css
repl/src/tutorial/tutorial.mdx

fix: 💄 Enhance visualisation of the Tutorial on mobile

---

packages/core/fraction.mjs
packages/core/strudel.mjs
packages/core/test/pattern.test.mjs

First run at squeezeBind, ref #32

---

packages/core/pattern.mjs
packages/core/speak.mjs
packages/core/strudel.mjs
repl/src/App.js
repl/src/tutorial/MiniRepl.jsx

Probably just a gimmick, but hey, it's there, it's fun, it's free

Speech output

---

packages/core/pattern.mjs
packages/core/signal.mjs

undegrade, sometimes, sometimesBy, sometimesByPre, often, rarely, almostNever, almostAlways, never, always
Ref #46 #31

More random functions

---

packages/embed/embed.js
packages/embed/example.html
repl/src/App.js

Added some repl styles that are only applied if it's embedded:
the emojis are shamelessly ripped off from https://hydra-book.glitch.me/

Embed style

---

packages/webaudio/scheduler.mjs

i cherry picked these changes from the starter-template branch:
- can now pass query latency, to prevent too tight deadlines
- now calling onTrigger automatically when set

Scheduler improvements

---

repl/package-lock.json
repl/package.json
repl/src/App.jsx

There is now a "share" button, which will generate a link by saving a random hash and the current code on [supabase](https://supabase.com/).

can now generate short link for sharing

---

packages/core/signal.mjs

as reported in https://github.com/tidalcycles/strudel/issues/167

fix: jsdoc comments

---

repl/src/App.jsx
repl/src/prebake.mjs

wait for prebake to finish before evaluating

---

packages/webaudio/webaudio.mjs
repl/src/prebake.mjs

as reported by @eefano , using numbers with piano did not work. this is now fixed

Fix numbers in sampler

---

packages/core/signal.mjs
packages/react/vite.config.js
tutorial/MiniRepl.jsx
tutorial/tutorial.mdx

document most of the random functions

document random functions

---

packages/core/controls.mjs
packages/webaudio/sampler.mjs
packages/webaudio/webaudio.mjs
tutorial/MiniRepl.jsx
tutorial/render.js
tutorial/tutorial.mdx

Webaudio guide

---

packages/core/pattern.mjs
packages/core/signal.mjs
tutorial/tutorial.mdx

- overall deduplication + restructuring
- now most of the actual function documentation is in source, the tutorial only references them
- documented some more functions
- marked tone + webdirt as deprecated

Even more docs

---

packages/core/pattern.mjs
tutorial/tutorial.mdx

- echo, echoWith
- iter, iterBack
- chunk, chunkBack

Just another docs PR

---

packages/webaudio/webaudio.mjs

- fix chop + loopAt
- unit
- nudge
- cut
- loop

sampler features + fixes

---

packages/webaudio/sampler.mjs
packages/webaudio/webaudio.mjs

ref https://github.com/tidalcycles/strudel/issues/195

support negative speeds

---

.gitignore
package-lock.json
package.json
packages/core/test/util.test.mjs
packages/core/util.mjs

I discovered Strudel a few days ago and am very excited by the project. I hope to get familiar with the internals and contribute where I can, but in the meantime I figured it couldn't hurt to write a couple of tests.

Core util tests

---

packages/core/pattern.mjs
packages/core/test/pattern.test.mjs
packages/core/timespan.mjs

Fix zero length queries WIP

---

packages/webaudio/reverb.mjs
packages/webaudio/worklets.mjs

audio worklets + reverb were only on one speaker

fx on stereo speakers

---

.github/workflows/test.yml
package-lock.json
packages/core/controls.mjs
packages/core/index.mjs
packages/embed/README.md
packages/embed/example.html
packages/mini/README.md
packages/mini/mini.mjs
packages/osc/README.md
packages/react/README.md
packages/react/src/App.jsx
repl/src/App.jsx

just some random improvements to the readmes and some minor code changes

Readme + TLC

---

package-lock.json
packages/tonal/package.json

fixes https://github.com/tidalcycles/strudel/issues/269

tonal update with fixed memory leak

---

.prettierignore
package-lock.json
package.json

add `npm run codeformat` to format all source files with prettier

add prettier task

---

packages/mini/mini.mjs

remove whitespace from highlighted region

---

packages/core/test/util.test.mjs
packages/core/util.mjs
packages/webaudio/sampler.mjs
packages/webaudio/webaudio.mjs
repl/src/prebake.mjs

`freq` did not work with samples yet. this is now possible. freq always wins against note / n

add freq support to sampler

---

.github/workflows/test.yml
.prettierignore
.prettierrc
package.json
packages/core/examples/vite-vanilla-repl/main.js
packages/core/hap.mjs
packages/core/pattern.mjs
packages/core/test/pattern.test.mjs
packages/core/timespan.mjs
packages/osc/server.js
packages/react/examples/nano-repl/vite.config.js
packages/react/index.html
packages/react/postcss.config.js
packages/react/src/main.jsx
packages/serial/serial.mjs
packages/soundfonts/list.mjs
repl/postcss.config.js
repl/src/index.css
tutorial/postcss.config.cjs

includes eslint + prettier checks in the test action to make sure the code is formatted (prettier) and does not include things that can lead to runtime errors (eslint) + ran a code format for the whole project

add lint + prettier check before test

---

packages/core/pianoroll.mjs

pianoroll now understands the freq param, allowing to visualize xenharmonic music

support freq in pianoroll

---

packages/core/test/util.test.mjs
packages/core/util.mjs
packages/transpiler/transpiler.mjs

fixes https://github.com/tidalcycles/strudel/issues/54

support notes without octave

---

packages/core/evaluate.mjs

fix: workaround Object.assign globalThis

---

package-lock.json
package.json
packages/core/pianoroll.mjs
website/src/pages/examples/index.astro
website/src/pages/img/example-[name].png.js
website/src/pages/learn/getting-started.mdx

with prerendered pianoroll swatches

add examples route

---

my-patterns/README.md
website/src/pages/my-patterns/[name].png.js
website/src/pages/my-patterns/index.astro
website/src/pages/my-patterns/list.json.js

adds my-patterns directory that automatically generates a /my-patterns page, displaying all files as clickable swatches

add my-patterns

---

packages/core/pianoroll.mjs
test/__snapshots__/tunes.test.mjs.snap
website/src/repl/tunes.mjs

+ added more color to some tunes
before:
after:

improve displaying 's' in pianoroll

---

packages/mini/krill-parser.js
packages/mini/krill.pegjs
packages/mini/mini.mjs

fix: can now multiply floats in mini notation

---

packages/core/animate.mjs
packages/core/index.mjs
packages/core/repl.mjs

mvp of canvas animation primitives to draw objects with patterns. it might make sense to move this to a separate package when it grows

animate mvp

---

packages/mini/krill-parser.js
packages/mini/krill.pegjs
packages/mini/mini.mjs
packages/mini/test/mini.test.mjs

Tidy parser, implement polymeters

---

packages/core/animate.mjs
packages/core/repl.mjs

- rescale + move + zoom for animate
- critifcal fix for mini repl (global scheduler nono)

more animate functions + mini repl fix

---

website/astro.config.mjs
website/src/components/HeadCommon.astro
website/src/components/Header/Header.astro
website/src/components/LeftSidebar/LeftSidebar.astro
website/src/components/PageContent/PageContent.astro
website/src/components/RightSidebar/RightSidebar.astro
website/src/components/RightSidebar/TableOfContents.tsx
website/src/pages/examples/index.astro
website/src/pages/learn/getting-started.mdx
website/src/pages/swatch/index.astro
website/src/repl/prebake.mjs

adds a base href to make sure links work on any subpath (be it strudel.tidalcycles.org or xxx.github.io/strudel etc..)
hopefully found all the broken links I've created with this change

Fix prebake base path

---

packages/core/test/pattern.test.mjs
packages/webaudio/webaudio.mjs

Fix .out(), renaming webaudio's out() to webaudio()

---

packages/core/signal.mjs
packages/core/test/pattern.test.mjs
test/__snapshots__/examples.test.mjs.snap
website/src/docs/JsDoc.jsx
website/src/pages/learn/factories.mdx

ref https://github.com/tidalcycles/strudel/issues/349

add run + test + docs

---

packages/core/animate.mjs
website/src/repl/drawings.mjs

+ add example drawings to separate file
ref https://github.com/tidalcycles/strudel/issues/370 + https://github.com/tidalcycles/strudel/issues/293

Rename a to angle

---

packages/react/src/components/Icon.tsx
packages/react/src/components/MiniRepl.jsx
website/src/docs/MiniRepl.astro
website/src/repl/Repl.css
website/src/styles/index.css
website/tailwind.config.cjs

fixes regression in https://github.com/tidalcycles/strudel/pull/396 where react styles were not present under some circumstances

fix: minirepl styles

---

packages/webaudio/webaudio.mjs

to be able to wait for worklets to be loaded before evaluation

can now await initAudio + initAudioOnFirstClick

---

packages/csound/package.json
pnpm-lock.yaml

ref https://github.com/tidalcycles/strudel/issues/402

pin @csound/browser to 6.18.3 + bump

---

packages/csound/index.mjs
packages/csound/package.json
pnpm-lock.yaml

see https://github.com/csound/csound/issues/1690#issuecomment-1414301145
fixes https://github.com/tidalcycles/strudel/issues/402

update csound + fix sound output

---

website/src/repl/Repl.jsx

fixes https://github.com/tidalcycles/strudel/issues/389

fix: share url on subpath

---

website/src/components/HeadCommon.astro
website/src/components/HeadSEO.astro

remove google fonts, they were not even used.. (gtfo = get the fonts out)

google gtfo

---

packages/core/controls.mjs
test/__snapshots__/examples.test.mjs.snap
website/src/pages/learn/samples.mdx

talk more about default samples, sound banks and selecting sounds

improve samples doc

---

my-patterns/README.md
pnpm-lock.yaml
website/astro.config.mjs
website/package.json
website/src/components/RightSidebar/RightSidebar.astro
website/src/components/RightSidebar/TableOfContents.tsx
website/src/docs/docs.css
website/src/repl/Repl.css

fixes https://github.com/tidalcycles/strudel/issues/432

Fix anchors

---

.prettierrc
website/src/pages/functions/intro.mdx
website/src/pages/functions/value-modifiers.mdx
website/src/pages/learn/accumulation.mdx
website/src/pages/learn/conditional-modifiers.mdx
website/src/pages/learn/csound.mdx
website/src/pages/learn/effects.mdx
website/src/pages/learn/factories.mdx
website/src/pages/learn/input-output.mdx
website/src/pages/learn/mini-notation.mdx
website/src/pages/learn/pwa.mdx
website/src/pages/learn/samples.mdx
website/src/pages/learn/signals.mdx
website/src/pages/learn/strudel-vs-tidal.mdx
website/src/pages/learn/time-modifiers.mdx
website/src/pages/learn/tonal.mdx
website/src/pages/technical-manual/alignment.mdx
website/src/pages/technical-manual/docs.mdx
website/src/pages/technical-manual/patterns.mdx
website/src/pages/technical-manual/repl.mdx

See https://prettier.io/blog/2021/09/09/2.4.0.html

FIXES: Warning about jsxBracketSameLine deprecation

---

packages/core/pattern.mjs
packages/core/test/pattern.test.mjs
test/__snapshots__/examples.test.mjs.snap

slice and splice

---

website/src/repl/Repl.jsx

hash links were broken for a second...

fix: hash links

---

packages/core/hap.mjs
packages/csound/index.mjs
packages/midi/midi.mjs
packages/osc/osc.mjs
packages/webaudio/webaudio.mjs
website/src/pages/learn/input-output.mdx

- now supports ccn and ccv
- also added midichan to select midi channel
- .midi now only chooses the output

midi cc support

---

website/src/components/HeadCommon.astro

for some reason, a scrollbar was shown on gnome, -1px fixed it

fix app height

---

packages/react/package.json
packages/react/src/components/MiniRepl.jsx

follow up for https://github.com/tidalcycles/strudel/pull/490

react style fixes

---

packages/core/pattern.mjs
test/__snapshots__/examples.test.mjs.snap
website/src/pages/learn/factories.mdx

fixes https://github.com/tidalcycles/strudel/issues/344

add arrange function

---

website/src/repl/Footer.jsx

Hi ! thanks a ton for strudle, amazing thing !

fix(footer): fix link to tidalcycles

---

packages/react/src/components/MiniRepl.jsx
website/src/repl/Repl.jsx

fixes https://github.com/tidalcycles/strudel/issues/528

fix period key for dvorak + remove duplicated code

---

packages/core/repl.mjs
packages/react/src/hooks/useStrudel.mjs
website/src/repl/Repl.jsx

fixes https://github.com/tidalcycles/strudel/issues/523

improve initial loading + wait before eval

---

packages/core/repl.mjs
website/src/repl/Repl.jsx

fixes https://github.com/tidalcycles/strudel/issues/517

do not reset cps before eval #517

---

website/src/repl/Loader.jsx
website/src/repl/Repl.jsx
website/tailwind.config.cjs

adds 2px animated loading bar to the top of the screen when evaluation is loading

feat: add loader bar to animate loading state

---

packages/mini/krill-parser.js
packages/mini/krill.pegjs

fix: allow whitespace at the end of a mini pattern

---

packages/core/cyclist.mjs

fixes https://github.com/tidalcycles/strudel/issues/498

fix: reset time on stop

---

packages/soundfonts/fontloader.mjs
test/runtime.mjs
website/src/repl/piano.mjs
website/src/repl/prebake.mjs

when pressing "shuffle", the soundfonts were unloaded. this is now fixed..

fix: load soundfonts in prebake

---

pnpm-lock.yaml
website/src/repl/prebake.mjs

- it broke the whole docs page
+ update lockfile to version 6 (pnpm 7.30.0 -> 8.3.1)

fix: make soundfonts import dynamic

---

packages/tonal/voicings.mjs

should have been there some time ago..

add basic triads and guidetone voicings

---

packages/core/util.mjs
website/src/repl/Repl.jsx

option+dot was not working on the main repl

Fix option dot

---

packages/core/util.mjs

fixes https://github.com/tidalcycles/strudel/issues/589

fix: allow f for flat notes like tidal

---

website/src/docs/MiniRepl.css
website/src/repl/Repl.css

- make cursor a little bit thicker
- use currentcolor -> fixes some themes were cursor was invisible
- disable blinking

improve cursor

---

packages/core/pattern.mjs
test/__snapshots__/examples.test.mjs.snap
website/src/pages/functions/value-modifiers.mdx

fixes https://github.com/tidalcycles/strudel/issues/601

add ratio function

---

packages/core/index.mjs
packages/core/spiral.mjs

`.spiral()` now draws a spiral to visualize events!

add spiral viz

---

packages/core/pattern.mjs
packages/core/repl.mjs

- loopAt now respects the current cps value
- add fit to repitch samples to fit hap duration
- add setcpm function

cps dependent functions

---

packages/core/pattern.mjs
test/__snapshots__/examples.test.mjs.snap
website/src/pages/learn/samples.mdx

fixes https://github.com/tidalcycles/strudel/issues/552

slice: list mode

---

website/src/repl/Repl.jsx

a random tune will only be loaded if no last session exists..

fix: welcome message for latestCode

---

packages/core/pattern.mjs

+ make dominantTrigger more dominant
fixes https://github.com/tidalcycles/strudel/issues/658

fix: always run previous trigger

---

packages/osc/osc.mjs

The clock from the audio context can drift over time, for me it is about +1 seconds every 20 minutes. 
When using the startedAt time as a reference, the drift can cause the ts value to be inaccurate and cause timing issues when sending the osc bundle. 
Instead, calculate the offset from the time values provided by the trigger and add them to the current time to ensure that the timestamp sent to the bundle is accurate.

fix osc bundle timestamp glitches caused by drifting clock

---

.eslintignore
website/src/repl/Footer.jsx
website/src/repl/Header.jsx
website/src/repl/Reference.jsx
website/src/repl/Repl.jsx
website/src/settings.mjs

a new setting for changing the position of the panel to the right
fixes https://github.com/tidalcycles/strudel/issues/600

togglable panel position

---

src-tauri/src/midibridge.rs

Adding a sleep timer of 1ms brings the cpu back down to where it should be.

add sleep timer + improve message iterating

---

packages/desktopbridge/midibridge.mjs

I believe the previous implementation wasn't sending CC messages, so I made a small fix.

fix MIDI CC messages

---

packages/superdough/dspworklet.mjs
packages/superdough/index.mjs
packages/webaudio/webaudio.mjs
website/src/repl/Repl.jsx

adds a live codable audio worklet à la https://github.com/felixroos/doughbeat

add dough function for raw dsp

---

packages/superdough/reverb.mjs
packages/superdough/superdough.mjs

in some cases, reverb regeneration could be triggered over and over again, see changes for more info.

fix: reverb regenerate loophole

---

packages/superdough/reverb.mjs
packages/superdough/reverbGen.mjs

reverb only worked with sample rate 44100

fix: reverb sampleRate

---

packages/core/signal.mjs
test/__snapshots__/examples.test.mjs.snap

[Bug Fix] chooseWith: prevent pattern from stopping audio when selection is >= 1 or < 0

---

website/astro.config.mjs

this hopefully fixes https://github.com/tidalcycles/strudel/issues/569

fix: trailing slash confusion

---

packages/superdough/sampler.mjs
test/__snapshots__/examples.test.mjs.snap
website/src/pages/learn/samples.mdx

Implements https://github.com/tidalcycles/strudel/issues/406

Add shabda shortcut

---

packages/superdough/synth.mjs
packages/webaudio/scope.mjs

fixes https://github.com/tidalcycles/strudel/issues/687

Fix addivite synthesis phases

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
website/src/repl/Repl.jsx

fixes https://github.com/tidalcycles/strudel/issues/642

fix: share copy to clipboard + alert

---

website/src/repl/Reference.jsx

Add function params in reference tab, like they are in autocomplete.

Add function params in reference tab

---

packages/webaudio/scope.mjs
test/__snapshots__/examples.test.mjs.snap

- the `pos` setting of the `scope` function was flipped
- also documented `scope` and `fscope`

Fix scope pos + document

---

packages/superdough/sampler.mjs

- use main branch by default in github shortcut
- add bubo shortcut

samples loading shortcuts:

---

website/src/repl/Reference.jsx

fixes https://github.com/tidalcycles/strudel/issues/790

don't use anchor links for reference

---

packages/core/repl.mjs

fix https://github.com/tidalcycles/strudel/issues/812

fix: multiple repls

---

packages/hydra/hydra.mjs

Another small one, but imho good to have. Allows to pass options to Hydra, and load personal forks of hydra-synth.

add options param to initHydra

---

packages/core/pattern.mjs
packages/core/test/pattern.test.mjs
test/__snapshots__/examples.test.mjs.snap
test/__snapshots__/tunes.test.mjs.snap

palindrome was doing abc -> cbaabc. This fix changes it to palindrome(abc) -> abccba.
see [discord](https://discord.com/channels/779427371270275082/937365093082079272/1180280656832495708)

FIXES: palindrome abc -> abccba

---

.github/workflows/deploy.yml
.github/workflows/test.yml

CHANGES: github action checkout from v2 to v4
Fixes #836

CHANGES: github action checkout v2 -> v4

---

website/src/pages/de/workshop/getting-started.mdx
website/src/pages/examples/index.astro
website/src/pages/learn/pwa.mdx
website/src/repl/prebake.mjs

A continuation of https://github.com/tidalcycles/strudel/issues/832, just a couple other small fixes that were missed.

Fix examples page, piano() and a few workshop imgs

---

.github/workflows/deploy.yml
.github/workflows/test.yml
CONTRIBUTING.md

https://github.com/tidalcycles/strudel/issues/833 is obsolete.

CHANGES: pnpm 8.1.3 to 8.11.0

---

packages/codemirror/codemirror.mjs
packages/codemirror/index.mjs
packages/codemirror/keybindings.mjs
packages/codemirror/themes.mjs
website/src/components/HeadCommonNew.astro
website/src/pages/vanilla/index.astro
website/src/repl/vanilla/vanilla.css
website/src/repl/vanilla/vanilla.mjs

- fontFamily setting
- fix draw
- fix keyboard shortcuts on linux
- fix theme style injects

Vanilla repl 3

---

packages/codemirror/codemirror.mjs

the selection was not visible, now it is

fix: invisible selection on vim + emacs mode

---

pnpm-lock.yaml

Update Vite version so hot reload works properly with newest pnpm version

---

website/src/pages/de/workshop/first-effects.mdx
website/src/pages/de/workshop/first-notes.mdx
website/src/pages/de/workshop/first-sounds.mdx
website/src/pages/de/workshop/pattern-effects.mdx
website/src/pages/de/workshop/recap.mdx
website/src/pages/workshop/first-effects.mdx
website/src/pages/workshop/first-notes.mdx
website/src/pages/workshop/first-sounds.mdx
website/src/pages/workshop/pattern-effects.mdx
website/src/pages/workshop/recap.mdx

Remove hideHeader for better mobile UI and consistency

---

.prettierignore
pnpm-lock.yaml
website/.astro/types.d.ts
website/package.json
website/src/components/BlogPost.astro
website/src/components/BlogVideo.astro
website/src/components/Header/Header.astro
website/src/components/PageContent/PageContent.astro
website/src/components/RightSidebar/MoreMenu.astro
website/src/components/RightSidebar/RightSidebar.astro
website/src/components/Showcase.jsx
website/src/config.ts
website/src/content/blog/release-0.0.2-schwindlig.mdx
website/src/content/blog/release-0.0.2.1-stuermisch.mdx
website/src/content/blog/release-0.0.3-maelstrom.mdx
website/src/content/blog/release-0.0.4-gischt.mdx
website/src/content/blog/release-0.3.0-donauwelle.mdx
website/src/content/blog/release-0.4.0-brandung.mdx
website/src/content/blog/release-0.5.0-wirbel.mdx
website/src/content/blog/release-0.6.0-zimtschnecke.mdx
website/src/content/blog/release-0.7.0-zuckerguss.mdx
website/src/content/blog/release-0.8.0-himbeermuffin.mdx
website/src/content/blog/release-0.9.0-bananenbrot.mdx
website/src/content/config.ts
website/src/env.d.ts
website/src/pages/blog.astro

so far added all release notes but there could be more. also added some more showcase videos

adds a blog

---

packages/core/cyclist.mjs
packages/core/pattern.mjs

Puts _cps in the pattern control state, as per #930

Make splice cps-aware

---

website/.astro/types.d.ts
website/src/content/blog/release-0.0.2-schwindlig.mdx
website/src/content/blog/release-0.0.2.1-stuermisch.mdx
website/src/content/blog/release-0.0.3-maelstrom.mdx
website/src/content/blog/release-0.0.4-gischt.mdx
website/src/content/blog/release-0.3.0-donauwelle.mdx
website/src/content/blog/release-0.4.0-brandung.mdx
website/src/content/blog/release-0.5.0-wirbel.mdx
website/src/content/blog/release-0.6.0-zimtschnecke.mdx
website/src/content/blog/release-0.7.0-zuckerguss.mdx
website/src/content/blog/release-0.8.0-himbeermuffin.mdx
website/src/content/blog/release-0.9.0-bananenbrot.mdx
website/src/content/blog/release-1.0.0-geburtstagskuchen.mdx

V1 release notes

---

packages/superdough/superdough.mjs
website/src/repl/Repl.jsx

fixes https://github.com/tidalcycles/strudel/issues/944

fix: reset global fx on pattern change

---

packages/core/controls.mjs
packages/core/pattern.mjs
packages/core/test/controls.test.mjs

poc for https://github.com/tidalcycles/strudel/issues/288
allows doing things like
```js
s("bd".pan(0))
```

Nested controls

---

packages/core/controls.mjs

the variable bag was a reference to the original object, the fix maintains immutability

little fix for withVal

---

packages/tonal/tonal.mjs

now this is supported:
```
"0 1 1b 1bb 1# 1## -2#".scale("c4:major").note().slow(4)
```

accidentals in scale degrees

---

packages/core/repl.mjs

fixes https://github.com/tidalcycles/strudel/issues/942

fix: await injectPatternMethods

---

packages/codemirror/codemirror.mjs
packages/codemirror/themes.mjs
packages/codemirror/widget.mjs
packages/core/cyclist.mjs
packages/core/hap.mjs
packages/core/pattern.mjs
packages/draw/draw.mjs
packages/draw/pianoroll.mjs
packages/draw/spiral.mjs
packages/repl/repl-component.mjs
packages/transpiler/transpiler.mjs
packages/webaudio/scope.mjs
website/src/docs/MiniRepl.jsx
website/src/repl/Repl.jsx

- visuals now follow the theme coloring by default
- various visual fixes
- add .tag method

better theme integration for visuals + various fixes

---

packages/core/pattern.mjs
test/__snapshots__/examples.test.mjs.snap

`beatCat` now `stepcat`, `timeCat` now an alias for `timecat` and tactus value is preserved a bit more.

Tactus tidy

---

website/astro.config.mjs

fixes https://github.com/tidalcycles/strudel/issues/1028

add font file types to offline cache

---

packages/codemirror/widget.mjs
packages/core/repl.mjs
packages/draw/index.mjs
packages/draw/pitchwheel.mjs
packages/tonal/voicings.mjs

draws a circle where each hap is a line from the center to the circle, where the angle is determined by its position within the octave.

pitchwheel visual

---

packages/core/pattern.mjs
packages/core/test/pattern.test.mjs

More step-oriented functions. Also group all the step-oriented functions together in the source.

Wax, wane, taper and taperlist

---

packages/core/util.mjs
packages/desktopbridge/midibridge.mjs
packages/desktopbridge/oscbridge.mjs
packages/midi/midi.mjs
packages/osc/osc.mjs
packages/osc/server.js
src-tauri/src/oscbridge.rs

also fixed osc server import that was failing

fix OSC timing for recent scheduler updates

---

website/src/repl/panel/WelcomeTab.jsx

Maybe we could add it to more places?

clarify license

---

website/src/pages/workshop/first-sounds.mdx

"per-cycle sequences" not sure if that's the best description though -

add `<...>` to first-sounds.mdx recap

---

website/src/pages/workshop/first-effects.mdx
website/src/pages/workshop/first-sounds.mdx
website/src/pages/workshop/pattern-effects.mdx

fix failing format test

---

packages/core/pattern.mjs
packages/mini/krill-parser.js
packages/mini/krill.pegjs
packages/mini/mini.mjs

Re-implement with weighted repeatCycles

Improve performance of ! (replicate)

---

packages/csound/index.mjs
packages/superdough/dspworklet.mjs

similar to osc / midi fixes, this one uses the newly added absolute time for csound and dough output

fix: csound + dough timing

---

bench/tunes.bench.mjs
package.json
packages/core/bench/pattern.bench.mjs
packages/core/package.json
packages/mini/bench/mini.bench.mjs
packages/mini/package.json

Just some simple benchmarks to get going

Benchmarks

---

website/src/repl/Repl.jsx

fixes #811
(started using Strudel with multiple tabs)

repl: set document.title from @title

---

.eslintrc.json
packages/sampler/package.json
packages/sampler/sample-server.mjs

probably fixes https://github.com/tidalcycles/strudel/issues/1105

Fix sampler windows

---

packages/superdough/superdough.mjs
packages/superdough/worklets.mjs

adding imports to the worklets file causes the deployed version not to compile correctly

Fix audio worklets

---

examples/codemirror-repl/main.js
examples/codemirror-repl/package.json
pnpm-lock.yaml

`drawPianoroll` is exported by `@strudel/draw` now.

Fixes drawPianoroll import in codemirror example

---

packages/superdough/superdough.mjs
website/src/repl/files.mjs
website/src/repl/idbutils.mjs
website/src/repl/panel/ImportSoundsButton.jsx

-converted base64 string to use blob storage instead
-existing files saved as strings will still load properly so no ones samples should go missing
-loading samples no longer processes one at a time so they upload much faster

Fix indexDB failing with large amount of files

---

packages/core/fraction.mjs
packages/core/test/pattern.test.mjs

lcm was always adding 1 to its arguments..

Fix bug in Fraction.lcm

---

website/src/repl/util.mjs

asking for pathname of parent location violates cors issue in iframes

[CORS HOTFIX]

---

packages/core/clockworker.js
packages/core/neocyclist.mjs
packages/core/util.mjs

created "clock collator"  utility for neocyclist that averages two clocks together to create a smooth output to the target clock. Will also use in the OSC timing improvements I have been working on.

Improve + simplify neocyclist timing

---

packages/core/pattern.mjs

Taking account of begin/end control parameters

Fixes fit so it works after a chop or slice

---

packages/midi/midi.mjs

improves error message when midi device name is invalid

handle midin device not found error

---

website/src/components/Header/Header.astro
website/src/repl/components/Header.jsx
website/src/repl/components/panel/ConsoleTab.jsx
website/src/repl/components/panel/Panel.jsx
website/src/repl/components/panel/WelcomeTab.jsx

colorize logs when color is set:
tweak header style:
- logo is now unicode symbol: ꩜
- removed icons for buttons (except play/stop) to make it less noisy

colorize console + tweak header

---

README.md

chore: Edit run locally instructions in README.md

---

packages/core/pattern.mjs

- Fix tactus returned by `steps`
- Fix name of toplevel s_extend (was `s_cycles`)

Add s_zip for 'cat'-ing patterns together step-by-step, bugfix `steps`

---

packages/mqtt/README.md
packages/mqtt/mqtt.mjs
packages/mqtt/package.json
packages/mqtt/vite.config.js
website/package.json
website/src/pages/learn/input-output.mdx
website/src/repl/util.mjs

Support for the MQTT internet-of-things protocol.
Fixes #1219

MQTT support

---

website/src/pages/functions/value-modifiers.mdx

Removes outdated examples from documentation in light of PR #1030

Update documentation for param value modification

---

packages/mqtt/mqtt.mjs

Helpful for cases where you don't want to risk putting a password in the code.

MQTT - if password isn't provided, prompt for one

---

packages/reference/README.md
packages/reference/index.mjs
packages/reference/package.json
packages/reference/vite.config.js
pnpm-lock.yaml

https://www.npmjs.com/package/@strudel/reference

add reference package

---

packages/soundfonts/sfumato.mjs
packages/superdough/superdough.mjs

fixes timing for sf2 soundfonts ( https://github.com/tidalcycles/strudel/pull/183 )

Fix sf2 timing

---

packages/core/pattern.mjs
packages/core/test/pattern.test.mjs

See https://github.com/tidalcycles/Tidal/issues/1053 for discussion

Fix `squeezejoin` and functions using it, including `bite` 

---

website/src/pages/learn/effects.mdx

This seems like it was a stray sentence left over from a refactor.

Fix misplaced ending sentence

---

packages/core/pattern.mjs

bugfix zoom stepcount

---

packages/superdough/synth.mjs
packages/superdough/worklets.mjs

TODO: add pulse width modulation lfo

feat: Create Pulse Oscillator  with variable PWM

---

packages/core/controls.mjs
test/__snapshots__/examples.test.mjs.snap

prevent pattern  from breaking if only one param is supplied

bugfix: Allow single param to be used in the as function

---

packages/superdough/helpers.mjs
packages/superdough/sampler.mjs
packages/superdough/superdough.mjs
packages/superdough/synth.mjs
packages/superdough/worklets.mjs
website/src/repl/components/panel/SettingsTab.jsx
website/src/repl/useReplContext.jsx
website/src/settings.mjs

feat: add max polyphony feature for superdough

---

packages/superdough/superdough.mjs
website/src/repl/components/panel/AudioDeviceSelector.jsx
website/src/repl/useReplContext.jsx
website/src/repl/util.mjs
website/src/settings.mjs

Mulitchannel audio device selection was sometimes failing due to a race condition. Moved all of the audio device setting logic to superdough where it belongs and refactored it.

FIX: Multichannel Audio 

---

website/astro.config.mjs
website/src/pages/udels/index.astro

now udels can be a PWA also :)

fix: udels header 

---

packages/core/controls.mjs
test/__snapshots__/examples.test.mjs.snap

example: 
https://strudel.cc/?hYMrL1YzSxUs

feat: Create scrub function for scrubbing an audio file

---

website/src/pages/learn/samples.mdx
website/src/repl/components/panel/SoundsTab.jsx

Made a small few changes in the docs to reflect the new import sounds folder UI.

update docs to reflect import sounds tab change

---

website/src/repl/idbutils.mjs

due to async behavior, the sounds would sometimes register in a non alphabetical order.

FIX: sound import order

---

packages/repl/package.json
packages/repl/vite.config.js
packages/web/package.json
packages/web/vite.config.js
pnpm-lock.yaml

follow up for https://github.com/tidalcycles/strudel/pull/1338 to fix repl and web package builds

Fix web + repl package builds

---

packages/codemirror/themes/CutiePi.mjs
packages/codemirror/themes/androidstudio.mjs
packages/codemirror/themes/atomone.mjs
packages/codemirror/themes/darcula.mjs
packages/codemirror/themes/dracula.mjs
packages/codemirror/themes/duotoneDark.mjs
packages/codemirror/themes/duotoneLight.mjs
packages/codemirror/themes/githubDark.mjs
packages/codemirror/themes/githubLight.mjs
packages/codemirror/themes/green-text.mjs
packages/codemirror/themes/gruvboxDark.mjs
packages/codemirror/themes/gruvboxLight.mjs
packages/codemirror/themes/red-text.mjs
packages/codemirror/themes/sonic-pink.mjs
packages/core/controls.mjs
packages/core/pick.mjs
packages/core/signal.mjs
test/__snapshots__/examples.test.mjs.snap

fixing some typos comments and things from #1349.

fix: typo on docs causing problems with autocompletion.
